# Generated by Django 3.0.3 on 2020-08-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
        migrations.RenameModel(
            old_name='AgentShifts',
            new_name='AgentShift',
        ),
        migrations.RenameModel(
            old_name='Shifts',
            new_name='Shift',
        ),
    ]
