# Generated by Django 3.0.3 on 2020-08-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_auto_20200806_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['surnames'], 'verbose_name': 'agente', 'verbose_name_plural': 'agentes'},
        ),
        migrations.AlterModelOptions(
            name='agentshift',
            options={'ordering': ['agent', 'shift_date'], 'verbose_name': 'turno_agente', 'verbose_name_plural': 'turnos_agente'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['name'], 'verbose_name': 'turno', 'verbose_name_plural': 'turnos'},
        ),
        migrations.AddField(
            model_name='agentshift',
            name='modified',
            field=models.BooleanField(default=False, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='cf',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='C.F.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='residence',
            field=models.CharField(max_length=20, verbose_name='Residencia'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='surnames',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='agentshift',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weekly.Agent', verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='agentshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weekly.Shift', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='agentshift',
            name='shift_date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(verbose_name='Inicio'),
        ),
    ]
