# Generated by Django 3.0.3 on 2020-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0003_auto_20200809_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentshift',
            options={'ordering': ['agent', 'shift_date'], 'verbose_name': 'turno agente', 'verbose_name_plural': 'turnos agente'},
        ),
        migrations.AlterField(
            model_name='agentshift',
            name='modified',
            field=models.BooleanField(verbose_name='Modificado'),
        ),
    ]
