# Generated by Django 3.0.3 on 2020-08-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0004_auto_20200809_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Residencia')),
            ],
            options={
                'verbose_name': 'residencia',
                'verbose_name_plural': 'residencias',
            },
        ),
        migrations.AlterField(
            model_name='agent',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='weekly.Residence', verbose_name='Residencia'),
        ),
    ]
