# Generated by Django 3.0.7 on 2020-08-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0007_auto_20200813_0654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
