# Generated by Django 3.0.3 on 2020-09-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0009_auto_20200830_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='residence',
            old_name='name',
            new_name='residence',
        ),
    ]
