# Generated by Django 3.0.3 on 2020-09-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0012_calendar_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='modified',
        ),
    ]
