# Generated by Django 3.0.3 on 2020-09-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0013_remove_calendar_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_id',
            new_name='calendar',
        ),
    ]
