# Generated by Django 3.0.3 on 2020-09-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0014_auto_20200918_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='agent_id',
            new_name='agent',
        ),
    ]
